#ifndef DARKCODE_INCLUDE_H
#define DARKCODE_INCLUDE_H
#include <QMouseEvent>
#include <QGraphicsOpacityEffect>
#include <QSplitter>
#include <QToolBox>
#include <QTabWidget>
#include <QTabBar>
#include <QPainter>
#include <TabPage.h>
#include <ui_TabPage.h>
#include <QString>
#include <QByteArray>
#include <QShortcut>
#include <QKeySequence>
#include <QTreeWidget>
#include <QTreeWidgetItem>
#include <Python_Editer.h>
#include <QFile>
#include <QTextStream>
#include <QMap>
#include "New_file_Dialog.h"
#include "ui_New_file_Dialog.h"
#include <QDateTime>
#endif // DARKCODE_INCLUDE_H
